version: '3'

services:
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres
        ports: 
            - "5432"
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    front:
      build:
        context: .
        dockerfile: Dockerfile_react
      restart: always
      volumes:
        - ./node:/usr/src/app:cached
      command: sh -c "cd django_front && yarn start"
      ports:
        - "3000:3000"
